---
title: "lfs_wage_analysis"
author: "Andrew Park"
date: "`r Sys.Date()`"
output: github_document
---

```{r}

library(sandwich)
library(lmtest)


lfs_raw_data <- read.csv("pub0626.csv")

str(lfs_raw_data) # Checks for strings
colnames(lfs_raw_data) #Looking at Col names (update this later)


cols_of_interest <- c("PROV", "LFSSTAT", "CMA", "AGE_12", "GENDER", "EDUC", "IMMIG", "COWMAIN", "HRLYEARN", "FINALWT")
lfs <- lfs_raw_data[, cols_of_interest]
``` 
#
#   PROV      - province code (10=NL, 11=PE, 12=NS, 13=NB, 24=QC,
#               35=ON, 46=MB, 47=SK, 48=AB, 59=BC)
#   LFSSTAT   - labour force status (1/2=employed, 3=unemployed, 4=NILF)
#   CMA       - census metro area, limited to the 9 largest on the PUMF
#   AGE_12    - age group with 12 categories
#   GENDER    - 1=Men+, 2=Women+ 
#   EDUC      - educational attainment
#   IMMIG     - immigrant status 
#   COWMAIN   - class of worker 1/2 = employees
#   HRLYEARN  - hourly earnings (2 implied decimals)
#   FINALWT   - survey weight

```{r}
# Cleaning the data
lfs_clean_data <- lfs[lfs$LFSSTAT %in% c(1,2) & lfs$COWMAIN %in% c(1,2) & !is.na(lfs$HRLYEARN) & lfs$HRLYEARN > 0 &
                        !is.na(lfs$IMMIG), ]
lfs_clean_data$HRLYEARN <- lfs_clean_data$HRLYEARN / 100 # 2 decimal points

lfs_clean_data$Immigrant <- ifelse(lfs_clean_data$IMMIG %in% c(1, 2), 1, 0)
lfs_clean_data$Urban    <- ifelse(lfs_clean_data$CMA != 0, 1, 0)
lfs_clean_data$log_wage <- log(lfs_clean_data$HRLYEARN)

# Sanity Check
table(lfs_clean_data$Immigrant)
table(lfs_clean_data$Urban)
table(lfs_clean_data$Immigrant, lfs_clean_data$Urban)

```
```{r}
# Regression Models

lfs_clean_data$log_wage <- log(lfs_clean_data$HRLYEARN)
str(lfs_clean_data$log_wage)

base_model <- lm(log_wage ~ Immigrant + Urban + factor(AGE_12), data = lfs_clean_data, weights = FINALWT)
summary(base_model)
```


```{r}
# Regression Model 2
# Interacting Immigrant * Urban

interaction_model <- lm(log_wage ~ Immigrant * Urban + factor(AGE_12), data = lfs_clean_data, weights = FINALWT)
summary(interaction_model)
```
```{r}
# F test: Does the Immigrant * Urban significantly improve the existing model?
anova(base_model, interaction_model)

```
```{r}
# Visualizing the Data
boxplot(log_wage ~ Immigrant + Urban, data = lfs_clean_data,
        names = c("Non-Imm.\nNon-CMA", "Imm.\nNon-CMA", "Non-Imm.\nCMA", "Imm.\nCMA"),
        ylab = "Log Hourly Wage",
        main = "Log Wage by Immigrant Status and Urban/Rural Region")
```


